### ISSUE TITLE
drag and drop support

### ISSUE THREAD

**Issue by efremidze** [bannzai/SpreadsheetView#1]
Idk if this is something that this repo should incorporate but just asking.

**Comment by kishikawakatsumi** [comment]
@efremidze I have a plan for supporting drag and drop or something editing features in the future. Currently, I'm focusing on improving stability and performance. Thanks.

**Comment by Miguel86** [comment]
Is there any possibility that drag and drop would be added?

**Comment by macchamps** [comment]
Hello, I also need this feature in the SDK. Can you please help ?
