### ISSUE TITLE
Colour Attributes don't work for columns

### ISSUE THREAD

**Issue by ikyh** [bannzai/SpreadsheetView#101]
@kishikawakatsumi   Hello..!! I am working on Schedule example.

## Expected Behaviour
Columns should have alternate darkGray and lightGray colour.

## Actual Behaviour
Initially when the app launches, the background colour for respective cells is filled in empty cells. Then upon scrolling horizontally, some cells are filled with background colour and some are not. Also the colour gets transferred to other column.  Also can you please add "Cell" UI part in the storyBoard. It is very difficult to understand the UI part from the code. Please Help!!

## Specifications

  - Xcode version: 8.2.1
  - iOS version: 
  - Dependency manager + version: 
![initial](https://user-images.githubusercontent.com/29946749/28363510-739ccf9a-6c9e-11e7-9c08-7baa9abad5ab.png)
![randomcell](https://user-images.githubusercontent.com/29946749/28363521-7a2d9d08-6c9e-11e7-9979-9bed2e7aaa08.png)
![coltrans](https://user-images.githubusercontent.com/29946749/28363526-7ff8a6c4-6c9e-11e7-9368-59fccb751313.png)

**Comment by kishikawakatsumi** [comment]
It seems to be a problem due to cell reusing. Did you reset the state correctly before the cell is reused?

Can you provide a reproducible code? @ikyh

**Comment by ikyh** [comment]
@kishikawakatsumi  Sorry I didn't. In which method do we have set that and How?? please help

**Comment by kishikawakatsumi** [comment]
@ikyh Your question is too broad and ambiguous. Explaining everything from scratch is inefficient. Please provide your current code.

**Comment by ikyh** [comment]
@kishikawakatsumi Hello....!! here is the code... I have made some changes in the frozen row and column cells according to my requirement. That is working fine except the column colours.
[ViewController.swift.zip](https://github.com/kishikawakatsumi/SpreadsheetView/files/1161529/ViewController.swift.zip)

![init](https://user-images.githubusercontent.com/29946749/28406388-02477272-6d4e-11e7-86ea-7a55484b2b8b.png)
![randomcells](https://user-images.githubusercontent.com/29946749/28406395-0a1c39ce-6d4e-11e7-9f11-8158eec3c93f.png)
![mixcol](https://user-images.githubusercontent.com/29946749/28406398-10eab1fe-6d4e-11e7-9bf2-0d3efe8bdf51.png)

**Comment by kishikawakatsumi** [comment]
@ikyh The first screenshot indicates an answer. Empty cells have a background color, but text cells don't.  You forgot (comment out) to assign `color` when the text is not empty. 

```
if !text.isEmpty {
    ...
    // You should also assign color in this case because cells are reused
    cell.color = indexPath.column % 2 == 0 ? evenColColor : oddColColor
}
else {
    ...
    cell.color = indexPath.column % 2 == 0 ? evenColColor : oddColColor
    ...
}
```

**Comment by ikyh** [comment]
@kishikawakatsumi Very small mistake I made. Thanks a lot..! It's working now..
