### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by Rufy86** [bannzai/SpreadsheetView#102]
Is it possible install manually the framework? if it is, how?

Thank you

**Comment by kishikawakatsumi** [comment]
Yes, it is. An easy way is to add a SpreadsheetView project to your project and specify it as embedded framework. Please look at projects in the examples directory. All of those projects are built using the way.

**Comment by Rufy86** [comment]
is there a easiest way? for example copy source code, o framework in the project?

because adding the project come out errors with info.plist file. in the project there are info.plist file that make conflict with the main project

**Comment by kishikawakatsumi** [comment]
Copying the source code should work, but that is a little bit harder way.
It is much easier to refer just as a subproject. Of course, if you choose copying source code, copy only the source code. Don't copy `Info.plist` or something else.

**Comment by kishikawakatsumi** [comment]
Or you can use pre-built binary. https://github.com/kishikawakatsumi/SpreadsheetView/releases
Just drag & drop `SpreadsheetView.framework` that is extracted from the zip file to `Embedded binaries` section.
