### ISSUE TITLE
Index out of range Exception for less number of rows or columns

### ISSUE THREAD

**Issue by ikyh** [bannzai/SpreadsheetView#108]
@kishikawakatsumi  Hi again, I have used Schedule app logic.  I have 4 columns and 3 rows. I am rendering the data array by transposing it. For eg. By your logic, [''1", "5", "9"] are placed in first row, but after transposing data array  ["1", "2", "3","4"] is placed in first row. 
```swift
let data = [
        ["1", "2", "3","4"],
        ["5", "6", "7", "8"],
        ["9", "10", "11", "12"]
        ]
```

Logic for Transpose:

```swift
public func transpose<T>(input: [[T]]) -> [[T]] {
        if input.isEmpty { return [[T]]() }
        let count = input[0].count
        var out = [[T]](repeating: [T](), count: count)
        for outer in input {
            for (index, inner) in outer.enumerated() {
                out[index].append(inner)
            }
        }
        
        return out
    }
```

When I reduce number of rows or columns, then I get "fatal error: Index out of range" exception on this line  ` let text = result[indexPath.column-1][indexPath.row-1]`.

 For eg.

```swift
        ["1", "2", "3"],     
        ["5", "6", "7"],
        ["9", "10", "11"],
        ]
```
or 

```swift
        ["1", "2", "3", "4"],
        ["5", "6", "7", "8"],
        ]
```

#Expected Behaviour
The remaining rows or columns should have "-" when no data is present. Please help.
I am using swift 3, Xcode 8.2.1

**Comment by kishikawakatsumi** [comment]
@ikyh Can you share your project? Your question is very unclear and you do not seem to understand the correct usage.

**Comment by kishikawakatsumi** [comment]
@ikyh SpraedsheetView's API is the same as UITableView/UICollectionView's manner. If there is any change in the data source, you must tell the view of the change using `reloadData()`.

**Comment by ikyh** [comment]
@kishikawakatsumi Hello..! It does not work. I have 5 columns but the grid data I am rendering to columns has 4 elements in the first row of an array. I am still getting Index out of bounds exception.
