### ISSUE TITLE
Make Cell.indexPath accessible

### ISSUE THREAD

**Issue by AStenzel** [bannzai/SpreadsheetView#109]
Hi @kishikawakatsumi, first of all, great job on this.

I'm trying to use SpreadSheetView as an editabel grid.
Therefore I have subclass cells in many different ways.
After editing a cell, i have to unselect the cell at cells indexPath. 
The problem is, that indexPath is inaccessible due to 'internal' protection level.

Is it possible to provide a getter for cells indexPath, e.g. 

```
public var cellIndexPath : IndexPath 
{
  get {
    return indexPath!
  }
}
```

Kind regards

**Comment by kishikawakatsumi** [comment]
@AStenzel You can add `indexPath: IndexPath` property and assign it yourself.

```swift
class TextCell: Cell {
    let label = UILabel()
    var indexPath: IndexPath?
    ...
```

```swift
func spreadsheetView(_ spreadsheetView: SpreadsheetView, cellForItemAt indexPath: IndexPath) -> Cell? {
    let cell = spreadsheetView.dequeueReusableCell(withReuseIdentifier: String(describing: TextCell.self), for: indexPath) as! TextCell
    cell.indexPath = indexPath
    ...
```

**Comment by AStenzel** [comment]
Yes, I know this solution, but why should I duplicate this variable when it's already available?

**Comment by kishikawakatsumi** [comment]
@AStenzel Because UITableViewCell and UICollectionViewCell don't expose `indexPath` property. Probably defining it yourself is enough in most use cases, I guess. It is not necessary to expose implementation details. I would like to keep the public API as small as possible for now.

**Comment by AStenzel** [comment]
Ok, thanks a lot.
