### ISSUE TITLE
SpreadsheetView scroll position jumps after reloadData if you freeze columns or rows

### ISSUE THREAD

**Issue by muratmusic** [bannzai/SpreadsheetView#110]
Please fix this problem

## Expected Behavior
SpreadsheetView should not change its scroll horizontal and vertical positions after reloadData method is called

## Actual Behavior
SpreadsheetView jumps after reloadData if you freeze columns or rows

## Steps to Reproduce the Problem
1. Freeze one column in ViewController of ClassData example project. To make it insert 
this data source method into ViewController
func frozenColumns(in spreadsheetView: SpreadsheetView) -> Int {  return 1  }
2. Build and run ClassData example project.
3. Scroll SpreadsheetView to see last column on the right
4. Tap on the top of the the last column to resort SpreadsheetView. It call reloadData method. You can see that SpreadsheetView horizontal scroll position jumps.

## Specifications

  - Xcode version: 9.0 beta 2 (9M137d)
  - iOS version: iPhone 5S Simulator with iOS 11
  - Dependency manager + version: we don't use any dependency manager at the moment

**Comment by ikyh** [comment]
Hello @kishikawakatsumi   I too face the same issue. I am working on TimeTable example. When I call spreadsheetview.reloadData(), the scrollView's position is shifted by 1 column and it starts showing the view from second column. (In terms of index positions - 2nd index). Please fix this issue. Thank you.

**Comment by muratmusic** [comment]
Hello @kishikawakatsumi

Thank you very much. I cannot reproduce this bug at the moment after checkout fix-jump-on-reload branch.

Many thanks!

**Comment by muratmusic** [comment]
It looks strange but I cannot scroll SpreadsheetView on my app after I checkout fix-jump-on-reload branch. Probably because I add SpreadsheetView as UIView on storyboard. SpreadsheetView on my app can be scrolled with master branch (with scroll-position bug).

Demo apps look great if I checkout fix-jump-on-reload branch.

**Comment by kishikawakatsumi** [comment]
@muratmusic Probably you've checked out WIP PR. Can you try the latest code? If you have any problems in the latest code, please open a new issue with reproduction. Thanks!

@ikyh
