### ISSUE TITLE
Sticky Rows and Columns can bounce

### ISSUE THREAD

**Issue by aelam** [bannzai/SpreadsheetView#112]
## Expected Behavior
1. Sticky Rows and Columns stick tightly on the borders 
2. vertical indicator would shake when dragging none-vertically and none-horizontally to make the header away from the top then release your hand

## Actual Behavior
Sticky Rows and Columns can bounce

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Xcode version: Xcode9-beta4
  - iOS version: iOS11-beta4
  - Dependency manager + version: ?

**Comment by kishikawakatsumi** [comment]
@aelam Can you provide your `SpreadsheetView`'s configuration? The best way is sharing your code around instantiating `SpreadsheetView` and setting its properties.

**Comment by kishikawakatsumi** [comment]
Closing due to no response. Please feel free to reopen this issue if you can provide more info/reproduction. Probably you seem to misunderstand the API.
