### ISSUE TITLE
IntrinsicContentSize

### ISSUE THREAD

**Issue by strangestlens** [bannzai/SpreadsheetView#114]
Hello!

I've got a question for you, and it revolves around the intrinsic content size. I have a need to build a component around your spreadsheet view, potentially stacking multiple spreadsheets within a single scroll view. To do this, it's important that we have support for intrinsicContentSize from the SpreadsheetView, and I'd like to know what you think the best way to approach this would be.

I wrote an extension that add this functionality in, but requires the SpreadsheetView, and a bit else in the framework, to be open instead of public. I know from a previous Issue that you'll add that in after you hit 1.0, so that's not something I'll ask about right now. I'd like to know if it makes sense to give some thought to this, or if I can make an addition akin to what I've written here and submit a pull request.

```
class HeightExpandableSpreadsheetView : SpreadsheetView {
	
	override var intrinsicContentSize : CGSize {
		
		return CGSize(width: frame.size.width, height: tableView.contentSize.height)
	}
	
	override func setNeedsLayout() {
		super.setNeedsLayout()
		invalidateIntrinsicContentSize()
	}
	
	override func refreshData() {
		super.refreshData()
		invalidateIntrinsicContentSize()
	}
}
```

I think, ultimately, it would make sense to make this a default behavior (well, for width and height, instead of just height as in my example), since this can all be ignored by setting size constraints anyway.

**Comment by strangestlens** [comment]
Another option might simply be to expose a getter that reports the spreadsheet view's contentSize.

**Comment by strangestlens** [comment]
Hi!  I ended up simplifying considerably, and have something that's working beautifully for our needs.

```
extension SpreadsheetView {
	override public var intrinsicContentSize : CGSize {
		
		let height = tableView.contentSize.height + rowHeaderView.contentSize.height
		let width = tableView.contentSize.width + columnHeaderView.contentSize.width
		
		return CGSize(width: width, height: height)
	}
}
```

and just adding `invalidateIntrinsicContentSize()` to the very end of `refreshData`

With this, I'm able to pack these spreadsheet views into individual components, and then stack those inside a scroll view, and everything resizing as expected. We've got the height abiding by intrinsicContentSize.height, and width we are restricting to its superview width.

**Comment by kishikawakatsumi** [comment]
@ideity Probably using `overlayView.contentSize` is much more simple and accurate instead? Also `SpreadsheetView.contentSize` returns `overlayView.contentSize`. So maybe you can write just `return contentSize`.

**Comment by strangestlens** [comment]
@kishikawakatsumi, that's a good call. Before data, there's a default height of 50 coming from somewhere, where overlay reports height of 0, but I think that's probably more accurate. And then once there's data to fill the spreadsheet out, contentSize matches my calculations, so that's surely the way to go.

**Comment by kishikawakatsumi** [comment]
It’s actually same behavior with UIScrollView, UITanleView and UICollectionView, I guess. I’m closing this issue. If you have further questions, please feel free to reopen the issue. Thanks!
