### ISSUE TITLE
Is it enable to add Pull-to-Refresh to its header?

### ISSUE THREAD

**Issue by aelam** [bannzai/SpreadsheetView#116]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Xcode version: ?
  - iOS version: ?
  - Dependency manager + version: ?

**Comment by kishikawakatsumi** [comment]
In theory, it is probably possible. Because spreadsheet view behaves almost same as scroll view. Do you have any specific problems?

**Comment by aelam** [comment]
Not try yet,  just researching the possibility. If it's not a scrollView maybe there is still some work to do to make it work with Pull-to-Refresh Control 

Multi floating sections like UITableView is also a problem to me. I can see your spreadsheet can set fixed  rows  columns by set a number in delegate methods, How about multi-sections  does it support?  For example I have two sections, when the second section header is on the top can i make it float on the top?

**Comment by kishikawakatsumi** [comment]
@aelam Spreadsheet view has no floating section header.

**Comment by kishikawakatsumi** [comment]
I'm going to close this issue. Hopefully, my answer helps you. Feel free to reopen or create a new issue if you need more help.
