### ISSUE TITLE
Scrollable content size looks like calculated for the first time only

### ISSUE THREAD

**Issue by muratmusic** [bannzai/SpreadsheetView#125]
## Expected Behavior

Scrollable content size should be recalculated every time after reloadData method is called

## Actual Behavior

If data source return 0 columns in numberOfColumns method for the first time then later you cannot scroll SpreadsheetView horizontally when data source return many columns in numberOfColumns method

Also if data source return many columns in numberOfColumns method for the first time then later you can scroll SpreadsheetView horizontally for large distance when data source return 1-2 columns and SpreadsheetView should not be scrollable

## Steps to Reproduce the Problem

  1. Make simple test app
  2. Let data source return 100 columns in numberOfColumns method for the first time. Be sure that your cellForItemAt method return correct cell to avoid crash.
  3. After some pause let data source return 1-2 columns in numberOfColumns. Call reloadData. You can scroll SpreadsheetView like you have 100 columns.

Probably this bug can be reproduced when numberOfRows change its returned value.

## Specifications

  - Xcode version: 9 beta 5
  - iOS version: 11
  - Dependency manager + version: No manager

**Comment by kishikawakatsumi** [comment]
@muratmusic Thank you very much for reporting! This is a regression in `v0.8.1`. It will be fixed very soon.

**Comment by muratmusic** [comment]
@kishikawakatsumi Many thanks
