### ISSUE TITLE
Check if spreadsheet is scrolled to bottom

### ISSUE THREAD

**Issue by kientux** [bannzai/SpreadsheetView#133]
I'm using latest version of SpreadsheetView. I'm finding a way to implement load more feature so I want  to know if spreadsheet is scrolled to bottom. I set delegate to scrollView of spreadsheet and check for `contentOffset`, `contentSize` but I can't find any relevant values between the two.

When I scrolled to bottom:
```
contentOffset: (302.0, 195.0) 
contentSize: (921.02099609375, 482.0)
```

Do you have any suggestion for this? Thanks.

**Comment by aidevjoe** [comment]
```
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        guard isPullable else { return }
        guard scrollView.contentSize.height > scrollView.bounds.height && scrollView.bounds.height > 0 else { return }
        let contentOffsetBottom = scrollView.contentOffset.y + scrollView.bounds.height
        if contentOffsetBottom >= scrollView.contentSize.height - (scrollView.bounds.height / 2) {
            isPullable = false
            
            DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 1, execute: {
                self.nextPage()
            })
            
        }
    }

```

This code can detect whether to scroll to the end, and I hope I can help you
But I found reloadData (). The data source has been modified, but the view has not changed. I don't know why

**Comment by kientux** [comment]
@Joe0708 Thank you, that's worked! I don't have problem with reloadData() though.

**Comment by hangocanh2303** [comment]
> ```
>     func scrollViewDidScroll(_ scrollView: UIScrollView) {
>         guard isPullable else { return }
>         guard scrollView.contentSize.height > scrollView.bounds.height && scrollView.bounds.height > 0 else { return }
>         let contentOffsetBottom = scrollView.contentOffset.y + scrollView.bounds.height
>         if contentOffsetBottom >= scrollView.contentSize.height - (scrollView.bounds.height / 2) {
>             isPullable = false
>             
>             DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 1, execute: {
>                 self.nextPage()
>             })
>             
>         }
>     }
> ```
> This code can detect whether to scroll to the end, and I hope I can help you
> But I found reloadData (). The data source has been modified, but the view has not changed. I don't know why

where you can place this function?
