### ISSUE TITLE
I got little problem of connecting to the storyboard.

### ISSUE THREAD

**Issue by Toyide** [bannzai/SpreadsheetView#134]
I can not create the SpreadSheetView on the storyboard, I know this is not an actually issue, Sorry about asking question here.  I'm new to Xcode, I tried many ways to connect the code to the storyboard views, literally stuck here for a whole day, any help will be really appreciated! Thanks in advance!
Following were what I do,

1. pod the newest version in the folder
2. run the project using the .wcworkspace
3.  type the code on the ViewController and try to get ( @IBOutlet weak var spreadsheetView: SpreadsheetView!)  hook with StoryBoard, failure.
4. drag the SpreadSheetView in the example file and put it in my StoryBoard, I do have the SpreadSheetView on my storyboard, but it seems still not connecting with my code, so failure again.
5. drag the frameworks from example folder to my project, I still unable to see the SpreadSheetView option in the object library...

Any help will be really appreciated! Thanks in advance!!

## Specifications

  - Xcode version: 8.3.3

**Comment by CoolHandLuke88** [comment]
I'm not sure about cocoapods as I am running Carthage and have not had chance to run it against cocoapods installation, however for carthage after installing SpreadsheetView. You will need to make sure your view is of class `SpreadsheetView` and module is also `SpreadsheetView` make sure `Inherit from Target` is unchecked. see screenshot below. Hope this helps you. I'll see about cocoapods a little later when I have time.
![screen shot 2017-09-03 at 5 43 26 pm](https://user-images.githubusercontent.com/1899958/30006831-bedde642-90cf-11e7-9575-83a03d441fc9.png)
