### ISSUE TITLE
Left hand borders clipped when no intercell spacing and no grids.

### ISSUE THREAD

**Issue by jsm174** [bannzai/SpreadsheetView#135]
I have a spreadsheet with no intercell spacing, and no grids.

For most of the cells, I have cell borders of 1 pixel solid.  For one cell, I want to make the left border thicker with 3 pixels. 

Since the borders are centered at the edges of the cell, my left pixel is being clipped.

![screen shot 2017-08-23 at 12 27 32 pm](https://user-images.githubusercontent.com/1197137/29627077-d8615c5e-87fe-11e7-8ffb-c52eaf522b7b.png)

For the heck of it, I put some insets in the spreadsheets tableView to prove it was being clipped:

```
tableView.contentInset = UIEdgeInsets(top: 5, left: 5, bottom: 5, right: 5)
```

![screen shot 2017-08-23 at 12 28 35 pm](https://user-images.githubusercontent.com/1197137/29627122-05c2536a-87ff-11e7-9471-158674d7f758.png)

Is there a way to have the spreadsheets tableview centered in the spreadsheetview?

**Comment by jsm174** [comment]
I cheated by adding extra empty columns (one on the left and one on the right) that were only a few pixels wide.

I guess it would be interesting if there was an option to center, ie if the spreadsheetView was 600 pixels wide, and the cell widths totaled 500 pixels, it could be centered at 50.

**Comment by kishikawakatsumi** [comment]
@jsm174 It's intended behavior currently. You should set 3 point spacing, then set 3 point grid and 1 point grid. But I'm considering to change the behavior. Thank you for reporting!
