### ISSUE TITLE
Get the value of row and column when cell is tapped

### ISSUE THREAD

**Issue by ikyh** [bannzai/SpreadsheetView#140]
Hello...! I am using Schedule App functionality. I have designed a custom gridCell to show JSON data in the rows and columns. In my case, I have to show first value in the gridCell, and remaining values in popUp View, when I tap on the cell.  I have made the view in the gridCell clickable, by using `UITapGestureRecognizer`.

In `cellForItemAt` I have called the `addGestureRecognizer(tapGesture)` to show the popUp. Like in` tableView` we can get the value of the row that was clicked in `didSelectRowAtIndexPath`, similarly how can I get the value of 1st column and 1st row **OR** (nth column and mth row). Also when I tap on the cell, The pop up appears, but `didSelectItemAt` does not get called because it does not show row and column number.
So, how to get row and column value when I click on particular cell so that I can pass this value as a request parameter to JSON to display corresponding cell's remaining values in the popUp.   Please help me with this. 
I think this feature is important like `uitableView`'s  get value of selected row. 

Many thanks :)

  - Xcode version: 8.2.1
  - iOS version: 10.11.5

**Comment by CoolHandLuke88** [comment]
Swift 3 implementation
see `SpreadsheetViewDelegate`
```func spreadsheetView(_ spreadsheetView: SpreadsheetView, didSelectItemAt indexPath: IndexPath)```

Also Note: indexPath has `row` and `column`.

**Comment by ikyh** [comment]
@CoolHandLuke88  @kishikawakatsumi    I have tried `didSelectItemAt`. If I call tapGesture in `func spreadsheetView(_ spreadsheetView: SpreadsheetView, didSelectItemAt indexPath: IndexPath)`  then the pop-up view appears when I click for 2nd time on cell. For 1st click on gridCell, I get value of row & column, For 2nd click the popUp appears and then after that on every click the pop-up appears. 

I want to get the value of row & column as well as the pop-up should appear on every click of the gridCell. After every click the cell should get deselect and when I click again the I should get the selected row-column value. I am plotting real time data on the cell, the data keeps on changing so I have to get new data on every click of the cell. 
Please help me with this. Thanks :)

**Comment by kishikawakatsumi** [comment]
@ikyh Could you share the sample project that reproduces the issue? I'm unclear what happens and why you are using `UITapGestureRecognizer`.

Technically, SpreadsheetView manages multiple scroll views to achieve complex layout. Gesture recognizers should work, but currently I cannot test all cases yet. So I'd like to know a lot of use cases and problems. @

**Comment by ikyh** [comment]
@kishikawakatsumi  Hello. When I tap on gridCell I have to pass the value of that cell in a request parameter. Since I get response from local host, I have not written the apiRequest func in this project. I have used dummy values. 

What I want is:
When user taps on the cell, a pop-up appears and the user sees the remaining values of the cell on pop-up. 
When I tap for the first-time on the cell, I get the selected row and column number and on second tap the pop-up appears. 
I don't want this behaviour. When I tap for the first time then the pop-up should appear. For every tap on the gridCell, I should get the value of the cell and pop-up should appear.
I have to call apiRequest func in `didSelectItemAt`, so that I can send the selected row and column value in the request parameters, to get the remaining values of that particular cell. 

Here is the project, Please help me with this. I am Sorry if I have done something wrong. Still in learning phase.
[Demo.zip](https://github.com/kishikawakatsumi/SpreadsheetView/files/1316936/Demo.zip)

**Comment by CoolHandLuke88** [comment]
@ikyh Please see comments starting with `// NOTE:`

I added a example for adding gestures to the cell. You were adding the gesture on `didSelectItemAt`. This is why you were having to double tap the cell to get the popover to show. (wrong place to add the gesture). see Cell.swift ValueCell for example use of adding a gesture to the cell (gesture code is all commented out as you don't need to add a gesture to get your desired result, but added it just in case you need it for whatever reason). You can currently run the code as is and it will give you your values as requested. The other issue I see with your code that is outside of your current problem with this library is the popover controller. There is a delay on it dismissing which causes the popover controller from showing until the current popover controller instance is completely dismissed. I recommend using a custom vc transition (see comments in `ViewController` for further details). 

Good Luck with the rest of your project!

[Demo.zip](https://github.com/kishikawakatsumi/SpreadsheetView/files/1319863/Demo.zip)

**Comment by CoolHandLuke88** [comment]
@kishikawakatsumi Thank you for this awesome library!

**Comment by ikyh** [comment]
@CoolHandLuke88  Thanks a lot for helping :)  I was getting IndexOutOfBounds Exception so I added the case for rows and columns in `didSelectItemAt`.  I have to show different values for every cell. When I tap on the cell, a request is sent to server, with request parameters as cell value (for eg. 16). Then I will get response for the respective cell and I will show those values in the pop-up.  So I will have to send the apiRequest in `didSelectItemAt` right?? and also set the new values in`showPopOver(with: rowValues)`   where `rowValues` will be new pop-up values. Correct??

**Comment by CoolHandLuke88** [comment]
@ikyh That is correct your new values should be passed in the show popover if that is how you require it to be. You might want to have a loading indicator when making the api request on `didSelectItemAt` then show the popover on the response data being shown via your popup. ```showPopOver(with: rowValues)``` can show your values returned from the server. just make sure your data is formatted to be array of strings. I tend to use this for a loading indicator. https://github.com/icanzilb/SwiftSpinner.

Good Luck!

**Comment by CoolHandLuke88** [comment]
@ikyh  If you have any questions you can message me directly. This issue should be resolved for you regarding the spreadsheetview. any questions regarding your project you can pm me, just let me know. I don't mind helping you if you have further questions.

**Comment by ikyh** [comment]
@CoolHandLuke88 Yup. Thanks for ur kind help!

**Comment by genaks** [comment]
I have a similar problem where I need to show a UIViewController on the tap of a cell but the UIViewController has to be presented as a popover. For this to happen, I will need to get the rect of the cell that was tapped on. I am doing this to get the rect of the cell - 

                let rect = self.gradebookView.rectForItem(at: indexPath)
                let rectInView = self.gradebookView.convert(rect, to: self.view)

but it seems the rect being obtained after converting it to the parent view's coordinate is not right and the popover always ends up getting opened someplace else and sometimes even out of the view. 

Thought this was related so I commented here.

**Comment by CoolHandLuke88** [comment]
Hello @genaks, Is this still issue you need help resolving?

**Comment by genaks** [comment]
No @CoolHandLuke88. I was able to work my around this. Thanks!
