### ISSUE TITLE
reloadData() in viewWillTransition doesn't work properly in Swift 4

### ISSUE THREAD

**Issue by Romores** [bannzai/SpreadsheetView#146]
## Expected Behavior
In my project, I have a view controller with a SpreadsheetView that autoresizes to the new size when rotating the device.

## Actual Behavior
In Swift 3, the behaviour is right: the device rotates and the spreadsheet resizes accordingly.
In Swift 4, this is not valid anymore: now, when you rotate the device, the spreadsheet resizes to the PREVIOUS size instead of the new one: basically, when you rotate the device to Portrait, the spreadsheet is resized to Landscape, and vice versa.

I tried building the old project in Swift 3, and it still works as it used to, so I'm not sure it's a problem of the library, or Apple changed the behaviour of viewWillTransition.

## Steps to Reproduce the Problem

The code is simple as that. Just put the viewWillTransition method in your view controller and rotate the device.

```
override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        spreadsheetView.reloadData()
    }
```

I also add the method to specify the new width of the columns:

```
func spreadsheetView(_ spreadsheetView: SpreadsheetView, widthForColumn column: Int) -> CGFloat {
        switch column {
        case 0:
            return spreadsheet.layer.frame.width/3
        default:
            let width = spreadsheet.layer.frame.width-(spreadsheet.layer.frame.width/3)-10
            return width/CGFloat(7)
        }
    }
```

## Specifications

  - Xcode version: 9
  - iOS version: 10 on the device, 11 on the simulator. They both have the same issue.
  - Dependency manager + version: CocoaPods - 0.7.2 on the Sw3 project, 0.8.4 on the Sw4 project.

**Comment by Romores** [comment]
I just tried to update the library on the Swift 3 project, and the problem still occurs. So I guess it's not a problem of Swift 4, but a bug in the 0.8.4 version.

**Comment by kishikawakatsumi** [comment]
@Romores I couldn't reproduce the issue, in Swift 3 and 4, on iOS 11. Could you please provide a reproducible sample project or more detailed code snippet?

**Comment by Romores** [comment]
I just tried to create a new project in Xcode to test it wasn't a problem from the original project. The problem still persists. This is the simplest case I could recreate.

```

override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        spreadsheetView.reloadData()
    }

extension ViewController: SpreadsheetViewDelegate, SpreadsheetViewDataSource {
    func numberOfColumns(in spreadsheetView: SpreadsheetView) -> Int {
        return 1
    }
    
    func numberOfRows(in spreadsheetView: SpreadsheetView) -> Int {
        return 1
    }
    
    func spreadsheetView(_ spreadsheetView: SpreadsheetView, cellForItemAt indexPath: IndexPath) -> Cell? {
        let cell = spreadsheet.dequeueReusableCell(withReuseIdentifier: String(describing: TextCell.self), for: indexPath) as! TextCell
        
        cell.backgroundColor = UIColor.lightGray
        cell.label.text = "Test text"
        
        return cell
    }
    
    func spreadsheetView(_ spreadsheetView: SpreadsheetView, widthForColumn column: Int) -> CGFloat {
        return view.frame.width
    }
    
    func spreadsheetView(_ spreadsheetView: SpreadsheetView, heightForRow row: Int) -> CGFloat {
        return view.frame.height
    }
}
```

Theorically, the spreadsheet should always autoresize to the screen size every time the device is rotated, and reloadData() is called in viewWillTransition, but it actually resizes to the PREVIOUS size (Portrait if Landscape, and Landscape if Portrait). I just tried it on my device as well (iPhone SE, iOS 11) and I experience the same issue.

If you can't replicate it, I've no idea of what problem my development environment could have...
The older 0.7.2 version didn't have this issue, but I can't use it anymore on the simulator because it crashes if I compile it in macOS 10.

**Comment by Romores** [comment]
And here's the Xcode project.

[spreadsheet.zip](https://github.com/kishikawakatsumi/SpreadsheetView/files/1325735/spreadsheet.zip)

**Comment by Romores** [comment]
Maybe I managed to solve the issue by enveloping the reloadData() method inside the transition coordinator.

```
super.viewWillTransition(to: size, with: coordinator)
    coordinator.animate(alongsideTransition: nil, completion: { _ in
    self.spreadsheet.reloadData()})
```
Like this, it seems to work again. It's still strange that it didn't need that before...

**Comment by kishikawakatsumi** [comment]
@Romores It seems working as expected. When `view*Will*Transition` invoked, `view.frame` still returns the frame before rotation. If you'd like to resize by rotation, it means that timing is too early. Enveloping the `reloadData()` method inside the transition coordinator seems right solution.

**Comment by amitabhis2903** [comment]
Is spreadsheet support UIRefresh control like table view
