### ISSUE TITLE
SIGABRT on simulator when showing a SpreadsheetView 

### ISSUE THREAD

**Issue by Romores** [bannzai/SpreadsheetView#147]
## Expected Behavior
Show the view controller containing a spreadsheet (in my case, you access the controllers via a tab bar)

## Actual Behavior
On the simulator, I get a generic SIGABRT error whenever I try to show a view controller containing a spreadsheet.

IT STILL WORKS ON AN ACTUAL DEVICE, the problem seems to only affect the simulator.

## Specifications

  - Xcode version: 9
  - iOS version: 10 on device, 11 on simulator
  - Dependency manager + version: CocoaPods, 0.7.2 in the Sw3 project, 0.8.4 in the Sw4 one.

**Comment by Romores** [comment]
Update: I tried to update the pod to the latest version, and now it seems to work in the simulator, too. I guess it was my fault for not trying before, sorry. The upgrade to Swift 4/iOS 11 really made me paranoid, since I use this library for my job and I really need it to work.

It now has the bug I mentioned in the previous thread, though.

**Comment by kishikawakatsumi** [comment]
@Romores Could you please share a reproducible sample project?

**Comment by Romores** [comment]
I don't think I can, unfortunately. But the issue was probably that I'm still using iOS 10 SDK to build the project (I've not yet upgraded to High Sierra). Then I saw the change log in the 0.8.4 version (_Fix to crash in iOS 11 if binary built with base SDK iOS 10. #138_) and that fixed the problem in the Swift 3 version of my project, too.

**Comment by kishikawakatsumi** [comment]
@Romores You meant this issue was resolved in `v0.8.4`, right? Can I close this issue?

**Comment by Romores** [comment]
Yes, I believe that was the case. As soon as I upgraded to the latest version it didn't crash anymore, so yes, you can close this issue.

**Comment by kishikawakatsumi** [comment]
@Romores Thank you for reporting!
