### ISSUE TITLE
SpreadsheetView delegate getting called before viewWillAppear

### ISSUE THREAD

**Issue by Romores** [bannzai/SpreadsheetView#155]
I think I understood why I started having issues once installed the new version of the library. The delegate methods of SpreadsheetView are now called BEFORE the viewWillAppear method of the view controller. I'm pretty sure it wasn't like that in previous versions.

I noticed this because there are certain operations for the spreadsheet that I used to do in the viewWillAppear, that I had to move inside of viewDidLoad for them to work because they started to lead me to unexplainable crashes, even if I hadn't modified anything in the logic, since I updated to the new version.

That is why, for example, the spreadsheet didn't follow the new frame size in viewWillTransition in the same manner as it used to: the delegates are called before viewWillAppear, so before the view frame has actually changed.

There are certain view controllers, in my project, where the size of the spreadsheet depends on the current screen orientation and size, and as now the viewWillAppear is getting called after the SpreadsheetView delegate methods, when the view is shown for the first time the cell size is wrong. Unlike before, I now have to force reload the spreadsheet a second time for it to show correctly...

Is this something that was changed on purpose, or am I the only one having this issue?

**Comment by kishikawakatsumi** [comment]
@Romores I cannot reproduce such behavior. There seems to be something different my setup and your setup. Could you share a reproducible project?

The following log is that I tried. All data source methods are called after `viewWillAppear`.

```
viewDidLoad
viewWillAppear
numberOfColumns
numberOfRows
frozenRows
spreadsheetView:widthForColumn:
spreadsheetView:widthForColumn:
spreadsheetView:widthForColumn:
spreadsheetView:widthForColumn:
spreadsheetView:widthForColumn:
spreadsheetView:widthForColumn:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:heightForRow:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
spreadsheetView:cellForItemAt:
viewDidAppear
```

**Comment by kishikawakatsumi** [comment]
Closing due to no response. Feel free to reopen you have further discussions.
