### ISSUE TITLE
can we add Search Bar on SpreadsheetView?

### ISSUE THREAD

**Issue by sameerkupkar** [bannzai/SpreadsheetView#157]
I am use SpreadsheetView pod, I design as my design requirement but i need add the Search bar on SpreadsheetView in Header section and search from table . can you help me please.

**Comment by kishikawakatsumi** [comment]
@sameerkupkar  Your question is too broad, it could be answered by an entire book, or has many valid answers. Please provide the code that you wrote.

**Comment by sameerkupkar** [comment]
Simply i want to add searchbar on header of spreadsheet can it possible?

**Comment by cemolcay** [comment]
You can simply add a search bar and spreadsheet view inside a vertical stack view or a custom container view and update the spreadsheet view's data as the search bar's text input changes.

**Comment by kishikawakatsumi** [comment]
@sameerkupkar Yes. Because SpreadsheetView is a subclass of UIView.

**Comment by sameerkupkar** [comment]
Any demo on that.still i am not getting answer.

**Comment by kishikawakatsumi** [comment]
@sameerkupkar You should provide a code that you tried (that probably doesn't work though, it's OK) at first. Because your question is too basic, ambiguous and broad. It takes too much time to teach all.

**Comment by sameerkupkar** [comment]
i am trying app like thinkorSwim trading app so i want spreadsheet with search bar.
