### ISSUE TITLE
Export/Share to pdf

### ISSUE THREAD

**Issue by JonasDeichelmann** [bannzai/SpreadsheetView#162]
Hi,

## Expected Behavior

For example, if the User want to share the generated Spreadsheet, then it could be useful to have a share function which creates a PDF out of the Spreadsheet.

## Actual Behavior

There is actually no way, to export the Spreadsheet to PDF.

## Specifications

  - Xcode version: ?
  - iOS version: ?
  - Dependency manager + version: ?

## 

Thanks for your work in this helpful framework.

**Comment by kishikawakatsumi** [comment]
@JonasDeichelmann Could you tell us a more detailed use cases? I don't think PDF export function needs to be included in this library. Drawing a view as PDF can be achieved with a few code using Core Graphics or PDF Kit API.

**Comment by JonasDeichelmann** [comment]
@kishikawakatsumi 
Thanks for your comment.
Yes, of course. When I embed this helpful API in my App, then I want to offer the user a function to share the created Spreadsheet with there people, with the third-party share function from Apple.
It would be really convenient just to create a PDF out of the Spreadsheet, exactly how it appears on the screen. I guess this function would be used many times.

**Comment by kishikawakatsumi** [comment]
@JonasDeichelmann I think it is better to implement it in each app. I think that is more flexible.  Is there a reason why it is better to implement the function on the library side? Converting view to PDF is very easy using CoreGraphics as I mentioned.

**Comment by kishikawakatsumi** [comment]
@JonasDeichelmann Also, if exporting PDF would be implemented on the library side, there are many specifications that I have to consider, such as setting of margins and page size. So the use cases I want to know is, what kind/appearance/format of PDF would you like to export?

**Comment by kishikawakatsumi** [comment]
Closed due to inactivity. Feel free to reopen if you have further discussion.
