### ISSUE TITLE
long tap cell and change backround all raw

### ISSUE THREAD

**Issue by SLACKWARE87** [bannzai/SpreadsheetView#164]
you can have the long tap event on the cell.
Also can you color the entire line at the touch of a cell?

**Comment by kishikawakatsumi** [comment]
I'm not sure I understand what you're asking.
Could you elaborate the question? Also please include any code you tried.

**Comment by SLACKWARE87** [comment]
sorry,

1) I want to add another action on the cell, this action has to start when the user makes a prolonged touch on the cell

2) I want to change the color background of the line when I touch a cell

I touch the cell (i, j) and I want to color all the columns (i, j-1j, j + 1)

**Comment by kishikawakatsumi** [comment]
@SLACKWARE87 

1. You can probably use `UILongPressGestureRecognizer` for the cell.

2. Modify data source when you touch a cell to change color, then `reloadData()`.

**Comment by kishikawakatsumi** [comment]
Closing due to no response
