### ISSUE TITLE
Swift 4 Updation?

### ISSUE THREAD

**Issue by Krishnaprasad66** [bannzai/SpreadsheetView#168]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Xcode version: ?
  - iOS version: ?
  - Dependency manager + version: ?

**Comment by kishikawakatsumi** [comment]
Already supported Swift 4. Do you have any problems?

**Comment by Krishnaprasad66** [comment]
Hi
Which version supported swift?
Could u give me pod file statement?

Thanks

**Comment by Krishnaprasad66** [comment]
Hi

Thanks for the reply
Could you give me the supported version to include in swift 4 project

**Comment by kishikawakatsumi** [comment]
@Krishnaprasad66 I don't know what you are asking. If your project uses Swift 4 (specified `SWIFT_VERSION = 4.0`), CocoaPods recognize it and set each pod's Swift versions to 4.0 automatically.

**Comment by Krishnaprasad66** [comment]
Okay..Fine..
