### ISSUE TITLE
dynamic width for column

### ISSUE THREAD

**Issue by joseph-517** [bannzai/SpreadsheetView#169]
Hi
How can i set dynamic width for column?

thanks

**Comment by kishikawakatsumi** [comment]
Same as UITableView or UICollectionView. Change data source first, then `reloadData`.

**Comment by joseph-517** [comment]
Hi
but i saw source code.
it's fixed.
func spreadsheetView(_ spreadsheetView: SpreadsheetView, widthForColumn column: Int) -> CGFloat {
            return 100
}

How can i set ?

Thanks

**Comment by kishikawakatsumi** [comment]
@starkite Return value should be variable. Change return value first, then call `reloadData()`. Same as UITableView API.
