### ISSUE TITLE
是否有Object-C版本的代码

### ISSUE THREAD

**Issue by zhj1214** [bannzai/SpreadsheetView#171]
是否有Object-C版本的代码

**Comment by kishikawakatsumi** [comment]
Closing due to duplicate https://github.com/kishikawakatsumi/SpreadsheetView/issues/43

@zhj1214 You can use this library with Objective-C.

**Comment by keshiim** [comment]
@zhj1214 https://github.com/keshiim/ZMJGanttChart 这里有OC版本
