### ISSUE TITLE
Fatal error : Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by bogo96** [bannzai/SpreadsheetView#172]
## Expected Behavior

i install the spreadsheet View on my project named schedule.

And I write the code like below in ViewController.swift.

and nothing in storyboard

also nothing in my simulator

**import UIKit
import SpreadsheetView

class ViewController: UIViewController,SpreadsheetViewDataSource{
    
    @IBOutlet weak var spreadsheetView: SpreadsheetView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        spreadsheetView.dataSource = self
    }
    
    func numberOfColumns(in spreadsheetView: SpreadsheetView) -> Int {
        return 10
    }
    
    func numberOfRows(in spreadsheetView: SpreadsheetView) -> Int {
        return 10
    }
    
    func spreadsheetView(_ spreadsheetView: SpreadsheetView, widthForColumn column: Int) -> CGFloat {
        return 80
    }
    
    func spreadsheetView(_ spreadsheetView: SpreadsheetView, heightForRow row: Int) -> CGFloat {
        return 40
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
    
}**

But i got an error like below where "spreadsheetView.dataSource = self" 

Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

I think it's because the value of spreadsheetView is nil

what should i do??

I use iMac.

Thank u.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Xcode version: ?
  - iOS version: ?
  - Dependency manager + version: ?

**Comment by kishikawakatsumi** [comment]
`spreadsheetView` seems `nil` obviously. `@IBOutlet` means it should be bound from Storyboard. You should place SpreadsheetView in storyboard and bind it to the variable. or you can instantiate the instance manually.
