### ISSUE TITLE
Append New Cell

### ISSUE THREAD

**Issue by bogo96** [bannzai/SpreadsheetView#173]
## Expected Behavior

when i tap the cell with empty string, make schedule cell into.

## Actual Behavior

error "Use of unresolved identifier 'cellForItemAt'"

## Steps to Reproduce the Problem

  1. add "addSubject(spreadsheetView, indexPath: indexPath, code: "cs204")" into delegate function
  2. make new function
 func addSubject(_ spreadsheet: SpreadsheetView, indexPath: IndexPath, code: String) {
        data[indexPath.column - 1][indexPath.row - 1] = code
        spreadsheetView(_, spreadsheetView: spreadsheet, cellForItemAt indexPath: indexPath)
    }
  3. 

## Specifications

  - Xcode version: 9.0
  - iOS version: swift 4
  - Dependency manager + version: ?

**Comment by kishikawakatsumi** [comment]
That's a syntax error. Probably it should be `spreadsheetView(spreadsheet, cellForItemAt: indexPath)`
