### ISSUE TITLE
Would be awesome if the SpreadsheetView cell have the option to add image

### ISSUE THREAD

**Issue by saormart** [bannzai/SpreadsheetView#175]
It's just a possible feature to have, an option to add image to the SpreadsheetView cell!
Just like we do have "cell.label" to set the label if we do have an option like: "cell.image" to add a image in the cell background wold be awesome!
I'm using the SpreadsheetView as a Grid, and if we could add a image on specific cells, we could have let's say "Button" (Visual for click), we could have "Check-Boxes" all as "Image" !
It's just an idea... don't know if it's hard to implement or not...
Thanks for the great framework!

**Comment by kishikawakatsumi** [comment]
@saormart You can do them with combinations of existing API, I guess.

**Comment by nboyd-sportdx** [comment]
indeed is it a great framework

i used an attribute string with an image in it to put an image in a cell

using [bonmot](https://github.com/Raizlabs/BonMot). you can create an attribute string and then

cell.label.attributedText = myAttributeString

**Comment by saormart** [comment]
Thanks guys I figure it out! :)
