### ISSUE TITLE
Command failed due to signal: Abort trap: 6

### ISSUE THREAD

**Issue by niravdesai** [bannzai/SpreadsheetView#177]
## Expected Behavior
1.	While type-checking 'HeaderCell' at /Users/projectname/Cells.swift:12:1
2.	While type-checking declaration 0x7fe0ea12ec58 at  /Users/projectname/Cells.swift:13:5
3.	While type-checking expression at [ /Users/projectname/Cells.switt:13:17 - line:13:25] RangeText="UILabel()"
4.	While loading conformances for 'Cell' in module 'SpreadsheetView'
5.	While reading inherited conformance for type 'Cell'
6.	While cross-referencing conformance for 'UIView' in module 'UIKit'
7.	While ... to 'CALayerDelegate' in module 'QuartzCore'
8.	If you're seeing a crash here, check that your SDK and dependencies are at least as new as the versions used to build 'SpreadsheetView'

## Actual Behavior
Project doesnot run

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Xcode version: 9.2
  - iOS version: iOS11 (Deployment target is : 8.2)
  - Dependency manager + version: SpreadsheetView version 0.8.4

**Comment by kishikawakatsumi** [comment]
Can you share reproducible sample project? @niravdesai

**Comment by kishikawakatsumi** [comment]
Closing due to lack of information. Feel free to reopen if you can provide more information. Thanks.
