### ISSUE TITLE
Can each cell fit to the content itself ?

### ISSUE THREAD

**Issue by StevenStarz** [bannzai/SpreadsheetView#181]
## Expected Behavior
I want to do something just like this, look at the column email the cell is fit to the content itself
![whatsapp image 2018-03-13 at 13 58 52](https://user-images.githubusercontent.com/22284886/37327136-a0fb6c06-26c7-11e8-9cd8-69fa83606750.jpeg)

## Actual Behavior
For now, all cell is same size, even the content is large than the cell

**Comment by StevenStarz** [comment]
@kishikawakatsumi

**Comment by kishikawakatsumi** [comment]
@StevenStarz It's expected by design. Since you know the maximum text width, you should return the appropriate column width from the data source yourself.

**Comment by StevenStarz** [comment]
its hard to guess, because the data is randomly inputted from user. @kishikawakatsumi, its impossible right,  i need to define the max width of each row.

**Comment by StevenStarz** [comment]
and i also need to define the max height of each column

**Comment by kishikawakatsumi** [comment]
@StevenStarz The only difference is whether it would be implemented on the library side or a programmer side. I have a plan to add such feature, but not yet. Thanks for the suggestion!
