### ISSUE TITLE
How to show selection on did select function

### ISSUE THREAD

**Issue by Vidhanshu09** [bannzai/SpreadsheetView#185]
## Expected Behavior
Show selection on didselect func

## Actual Behavior
Not showing any selection 

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Xcode version: 9
  - iOS version: 11
  - Dependency manager + version: ?

**Comment by kishikawakatsumi** [comment]
@Vidhanshu09 Same as UICollectionView API. Set `selectedBackgroundView` your custom cell. `selectedBackgroundView` is hidden normally, when you select a cell, then `selectedBackgroundView` is shown.
