### ISSUE TITLE
Change font size depending on system font size

### ISSUE THREAD

**Issue by prikhodkoalexey** [bannzai/SpreadsheetView#188]
## Expected Behavior
Font size changes if system font size changes.

## Actual Behavior
Font size stays the same.

## Steps to Reproduce the Problem

  1. Launch ClassData example project.
  1. Go to system preferences on the simulator device and change system font size.
  1. Go back to your application and see that font size hasn't changed.

## Specifications

  - Xcode version: 9.3 
  - iOS version: 11.2
  - Dependency manager + version: non, just example project

**Comment by kishikawakatsumi** [comment]
ClassData project is sample project focused explaining library usage. I do not want to write unrelated code like dynamic type. Also, unlike UITableView, SpreadsheetView doesn't have any built-in text label. So, if you'd like to add dynamic type support with this library, you need to implement it yourself.
