### ISSUE TITLE
How can I remove the gaps between spreadsheet and screen

### ISSUE THREAD

**Issue by bayfatih2000** [bannzai/SpreadsheetView#191]
## Expected Behavior
I want to remove the gaps. Do you have any suggestion? 

## Actual Behavior
![image1](https://user-images.githubusercontent.com/2362582/40773920-f254aa66-64cc-11e8-850c-5545250727cf.png)

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Xcode version: 9.4
  - iOS version: 11.3.1
  - Dependency manager + version: ?

**Comment by kishikawakatsumi** [comment]
@bayfatih2000 You probably misconfigured it. Can you please share a sample project which reproduces the issue?

**Comment by bayfatih2000** [comment]
The image occurs while scrolling. Normally, it has no problem. I want to finish the scroll when come to first/last row/column. Is it possible?

**Comment by xiaoruiling** [comment]
@bayfatih2000 :  xxx.bounds = false

**Comment by bayfatih2000** [comment]
"bounds" waits CGRect type. How can I set boolean value?

**Comment by bayfatih2000** [comment]
Ops. I understand now. bounces must be false. Thank you very much.
