### ISSUE TITLE
Can't draw a line in this Cell

### ISSUE THREAD

**Issue by xiaoruiling** [bannzai/SpreadsheetView#192]
## Expected Behavior
I want to draw a line on the cell, but it doesn't show

`
override func draw(_ rect: CGRect) {

    guard let context = UIGraphicsGetCurrentContext() else { return }

    let path = CGMutablePath()

    path.move(to: CGPoint(x:10, y:0))

    path.addLine(to:CGPoint(x:10, y:56))

    context.addPath(path)

    context.setLineWidth(10)

    context.setStrokeColor(UIColor.red.cgColor)

    context.strokePath()

  }
`
The code is correct that cells inherited from the UItableViewCell display a 10-pixel straight line, but cells inherited from SpreadsheetView do not display correctly

**Comment by xiaoruiling** [comment]
@kishikawakatsumi

**Comment by kishikawakatsumi** [comment]
@xiaoruiling Can you share a sample project that reproduces the issue?

**Comment by xiaoruiling** [comment]
`

     class HourCell: Cell {
        let label = UILabel()

       override init(frame: CGRect) {
        super.init(frame: frame)
        label.frame = bounds

        label.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        label.backgroundColor = UIColor.green
        label.font = UIFont.systemFont(ofSize: 12)
        label.textColor = .white
        label.textAlignment = .center
        label.numberOfLines = 2

         addSubview(label)
      }

       required init?(coder aDecoder: NSCoder) {
          super.init(coder: aDecoder)
       }
  
     override func draw(_ rect: CGRect) {
      guard let context = UIGraphicsGetCurrentContext() else { return }
      debugPrint("\(context)")
      let path = CGMutablePath()
      path.move(to: CGPoint(x:10, y:0))
      path.addLine(to:CGPoint(x:10, y:100))
      context.addPath(path)
      context.setLineWidth(10)
      context.setStrokeColor(UIColor.red.cgColor)
      context.strokePath()
        }
      }
`

you can put this code replace the  example of HourCell in Timetable , and HourCell can not show a red line
