### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by robertomoo** [bannzai/SpreadsheetView#195]
## Expected Behavior
I want to put a button no a cell

## Actual Behavior
My problem is that I can’t even show the button, wanna know if it’s possible to do and how is the better way to achieve

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Xcode version: 9.4.1
  - iOS version: 11.3
  - Dependency manager + version: Cocoapods

**Comment by kishikawakatsumi** [comment]
Please share a reproducible sample project.

**Comment by robertomoo** [comment]
this is the code I wrote to make a cell

`class ButtonCell: Cell {
    let label = UILabel()
    override init(frame: CGRect) {
        super.init(frame: frame)
        label.frame = bounds
        label.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        label.font = UIFont.boldSystemFont(ofSize: 12)
        label.textAlignment = .justified
        label.textColor = .black
        contentView.addSubview(label)
        let button = UIButton()
        button.setTitle("", for: .normal)
        button.setTitleColor(UIColor.blue, for: .normal)
        self.addSubview(button)
        button.addTarget(self, action: Selector(("buttonpressed:")), for: .touchDragInside)
    }
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }`

and this for the viewcontroller, probably need other thing but I'm not sure

`        if case (0,5) = (indexPath.column, indexPath.row){
            let cell = spreadsheetView.dequeueReusableCell(withReuseIdentifier: String(describing:ButtonCell.self), for: indexPath) as! ButtonCell            
            return cell
        }
        return nil
    }`

**Comment by saormart** [comment]
@robertomoo, I had the same situation and also I wanted to add an image into a cell, so you can add a image of a desired button, and capture the selected column index...
Here is the code I used to add image (in my case was a image of "Delete Button")...

`func spreadsheetView(_ spreadsheetView: SpreadsheetView, cellForItemAt indexPath: IndexPath) -> Cell? {

	//Change the "case 0" to any column index you need...
	if case 0 = indexPath.column {
                //This is how to add image to the Grid cell as icon...
                let fullString = NSMutableAttributedString(string: "") //can add text here
                let image1Attachment = NSTextAttachment()
                image1Attachment.image = UIImage(named: "DeleteBtnIco") //Image Name
                //resize the image:
                let rect = CGRect(origin: .zero, size: CGSize(width: 118, height: 48))
                image1Attachment.bounds = rect                
                let image1String = NSAttributedString(attachment: image1Attachment)
                fullString.append(image1String)
                fullString.append(NSAttributedString(string: "")) //can add text here
                cell.label.attributedText = fullString
            }

}`

**Comment by kishikawakatsumi** [comment]
Please provide executable sample project that reproduces the issue. I don't have enough time to debug your code.

**Comment by robertomoo** [comment]
here is an example of my project I can replicate the help that bring me @saormart, but I'm a little confused about the button
[Calendario.zip](https://github.com/kishikawakatsumi/SpreadsheetView/files/2139762/Calendario.zip)

**Comment by robertomoo** [comment]
I solve my problem so far, but I get other issue about how the cells realoaddata, cause when I put an attribute to the button the refresh or something make the buttons get filled by the attribute randomly, I'm attaching the newest version. Hope can help me.
[Calendario.zip](https://github.com/kishikawakatsumi/SpreadsheetView/files/2178779/Calendario.zip)

**Comment by DITIOF** [comment]
@saormart Can you guide me how to complete "delete button" function and how to catch its event to remove a row (not a cell) from SpreadSheetView . Thanks in advance
