### ISSUE TITLE
Keyboard sliding up and cover UITextField/UITextView

### ISSUE THREAD

**Issue by huforrest** [bannzai/SpreadsheetView#198]
In my spreadsheet view, I have many cells that contain textfield. And when keyboard slides up, some UITextField/UITextView are covered. And I have tried to solve this problem by adding the following code but failed. Here is the code:

    spreadsheetView.contentInset.bottom = keyboardHeight
    spreadsheetView.scrollIndicatorInsets.bottom = keyboardHeight

And my question is: Are the contentInset and scrollIndicatorInsets properties of spreadsheet view working fine? And how do I solve this problem?

**Comment by saormart** [comment]
@huforrest, I had a similar problem, and I fixed with: [IQKeyboardManager](https://github.com/hackiftekhar/IQKeyboardManager)
Hope this help you!

**Comment by huforrest** [comment]
@saormart Thank you very much. IQKeyboardManager solved my problem.

**Comment by saormart** [comment]
@huforrest  no problem buddy! Glad it worked for you!
