### ISSUE TITLE
Loading Time

### ISSUE THREAD

**Issue by arzath** [bannzai/SpreadsheetView#201]
Hi, I have noticed the  SpreadsheetView is taking significant time to display.
That is, the sheet won't be displayed until the entire sheet (of 50 * 13+) is finished loading but that takes 8+ seconds.

Is this normal?
If so, how do you tackle the problem? i.e. display partial data while loading (would appreciate if share the how-to)?

## Expected Behavior
Loading 50 rows x 13 columns sheet. Expecting loading to be done under 2 seconds.

## Actual Behavior
Loading 50 rows x 13 columns sheet resulting loading time in upwards of 8 seconds.

## Specifications

  - Xcode version: 9.3
  - iOS version: 11+

**Comment by kishikawakatsumi** [comment]
Please provide a reproducible sample project. The issue depends on what you wrote. @arzath

**Comment by saormart** [comment]
@arzath, I'm using this great framework and I have a screen where I'm loading over 4000 rows and 18 columns in a second....
As @kishikawakatsumi says, the issue depends on what you wrote!

**Comment by arzath** [comment]
@saormart Thanks for the tip, it saved me from wasting time on the wrong direction.
@kishikawakatsumi Thanks for the response, however I'm not at the liberty to provide what you ask for. I do have the the Instruments profile that indicates my call to SpreadsheetView.layoutSubview() is being called in upwards of tens of thousands times, and LayoutEngine.layout has the line 

> let stop = enumerateColumns(currentRow: row, currentRowIndex: rowIndex)

being called 2000+ times. With the info provided by @saormart's, this seems to be the pain point.

It would be awesome if you are able to provide your insight though with such limited information.

Thanks guys!

**Comment by arzath** [comment]
@kishikawakatsumi This can be closed, thanks for your attention.
