### ISSUE TITLE
When do you support swift4.2?

### ISSUE THREAD

**Issue by Pr-Chen** [bannzai/SpreadsheetView#208]
When do you support swift4.2?

**Comment by saormart** [comment]
same here !

**Comment by kishikawakatsumi** [comment]
@Pr-Chen @saormart Soon. But you can use this library with your Swift 4.2 project as-is.

**Comment by Faydee1220** [comment]
Still need to change Swift Language Version to Swift 4 manually to build.

**Comment by rgmyyw** [comment]
Swift4.2 not support !
