### ISSUE TITLE
Incompatible Swift version - framework was built with 3.1

### ISSUE THREAD

**Issue by panncherry** [bannzai/SpreadsheetView#243]
## Expected Behavior
*** Downloading SpreadsheetView.framework binary at "v0.8.4"

## Actual Behavior
***  Skipped installing SpreadsheetView.framework binary due to the error:
	"Incompatible Swift version - framework was built with 3.1 (swiftlang-802.0.53 clang-802.0.42) and the local version is 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)."

## Steps to Reproduce the Problem

  1. Download SpreadsheetView via Carthage
  2. Configure input-output file path in build phase setting

## Specifications

  - Xcode version: 11.6
  - iOS version: 13
  - Carthage: 0.35

**Comment by bannzai** [comment]
I fixed about swift version problem that SpreadsheetView supported swift 5. I will release it and I close this PR. Thank you your contributions 👍 

https://github.com/bannzai/SpreadsheetView/pull/256
