### ISSUE TITLE
didSelectItemAt not always called

### ISSUE THREAD

**Issue by zapjonny** [bannzai/SpreadsheetView#26]
I have trouble getting didSelectItemAt called for tapped cells, or even UIButton:s added to cells. Sometimes the didSelectItemAt is called, but mostly not. Somehow it's more often called when I tap on cell edges, but it might be just a coincidence...
UIButton:s aren't tappable at all for now.

BTW I am still experimenting with the Timetable sample app.

The above happens if I use just one or two channels. **Update:** I confirmed that if I use the default channels 

```
    let channels = [
        "ABC", "NNN", "BBC", "J-Sports", "OK News", "SSS", "Apple", "CUK", "KKR", "APAR",
        "SU", "CCC", "Game", "Anime", "Tokyo NX", "NYC", "SAN", "Drama", "Hobby", "Music"]

```

taps seem to work ok (didSelectItemAt at least)

If I use 

```
	let channels = [
		"ABC"]

```

taps do not work well; mostly only when I tap on the grid lines between cells.

**Comment by kishikawakatsumi** [comment]
Thank you for reporting and investigating. I'll figure out what happens later soon.

**Comment by kishikawakatsumi** [comment]
@zapjonny Could you try https://github.com/kishikawakatsumi/SpreadsheetView/pull/31 if you get a chance?

**Comment by zapjonny** [comment]
@kishikawakatsumi It seems like tapping on a cell works good now. Thanks!!
Still a UIButton inside a cell cannot be tapped still. I'm not sure why...

**Comment by kishikawakatsumi** [comment]
> UIButton inside a cell cannot be tapped still. I'm not sure why...

I forgot to read that sentence, sorry. I'll investigate soon.

**Comment by zapjonny** [comment]
BTW I think the way `UITableView` allows touches to UIButton:s etc, is something that has to do with `delaysContentTouches` of `UIScrollView`.

**Comment by zapjonny** [comment]
@kishikawakatsumi so #31 seems OK so far for the `didSelectItemAt` part. Will you merge that?
