### ISSUE TITLE
spreadsheetView.dataSource = self crashing

### ISSUE THREAD

**Issue by codewithsanthoshofficial** [bannzai/SpreadsheetView#274]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Xcode version: ?
  - iOS version: ?
  - Dependency manager + version: ?

**Comment by likil33** [comment]
@IBOutlet weak var spreadsheetView: SpreadsheetView! (taken outlet - used UIView)

spreadsheetView.dataSource = self.   - crashing
        spreadsheetView.delegate = self

why it is not initialise.

**Comment by jamesjmtaylor** [comment]
> ## Expected Behavior
> ## Actual Behavior
> ## Steps to Reproduce the Problem
> 
> ## Specifications
> * Xcode version: ?
> * iOS version: ?
> * Dependency manager + version: ?

For those developers that encounter this crash, the solution is below:

1. On the storyboard click on your SpreadsheetView
2. On the right panel select "Identity Inspector"
3. Under 'Custom Class' set the Module to SpreadsheetView and not to your target.
(in case you didn't set it the view should be a SpreadsheetView class (also under 'Custom Class'))
