### ISSUE TITLE
I think protocol should inherit from AnyObject.

### ISSUE THREAD

**Issue by keisukeYamagishi** [bannzai/SpreadsheetView#278]
## Expected Behavior

I think protocol should inherit from AnyObject.
As described in the following article, the specification is such that if you do not inherit AnyObject in protocol, you will get a warning.
[Swift forums 'Class-only protocols, class vs AnyObject?'](https://forums.swift.org/t/class-only-protocols-class-vs-anyobject/11507)

## Actual Behavior
Since the class is inherited by protocol, we get a `warning`.

## Steps to Reproduce the Problem

  1. Build with Xcode

## Specifications

  - Xcode version: 12.5
  - iOS version: 14.0
  - Dependency manager + version: n/a

**Comment by bannzai** [comment]
> As described in the following article

Maybe swift forum link is https://forums.swift.org/t/class-only-protocols-class-vs-anyobject/11507.
