### ISSUE TITLE
Doesn't work with Storyboard? I cannot set delegate and dataSource

### ISSUE THREAD

**Issue by leobartowski** [bannzai/SpreadsheetView#280]
## Expected Behavior
If i create a UIView and then try to assign the SpreadsheetView Class, I cannot set delegate and datasource and the apps crash!

## Specifications

  - Xcode version: 13
  - iOS version: 15

**Comment by cemsertkaya** [comment]
++

**Comment by amrzayed** [comment]
+1

**Comment by YoshiyukiNakazato** [comment]
You should also assign SpreadsheetView in Module.
