### ISSUE TITLE
A view added to a spread sheet view doesn't scroll

### ISSUE THREAD

**Issue by zapjonny** [bannzai/SpreadsheetView#33]
With a normal UITableView, I was able to have "overlay" views inside the tableview. The overlay views could really be shown "on top" of rows, just by adding them as subviews of the tableview itself. I tried this with SpreadsheetView but wasn't immediately able to. Would I need to add an overlay view to the internal "tableView" (which looks like a scrollview), or what is your suggestion?

**Comment by kishikawakatsumi** [comment]
I think the behavior adding a subview to the spreadsheet view is the same as `UITableView`'s. If you add the view directly as a subview of `UITableView`, the view scrolls together, right? To overlay it needs to be added to the `superview` of `UITableView`, I guess.

To be clear, could you share a code what you are doing and a code with `UITableView`? @zapjonny

**Comment by zapjonny** [comment]
Yes, it scrolls with the rows in the`UITableView`, and that is what I needed it to do. This is useful to show a current "timeline" on top of the current program in a timetable, which is what I actually use it for.
There might be other ways to implement that, like adding to the superview of the tableview/spreadsheetview as you mention. But I had it working pretty good, I just add a view to the uitableview, and a constraint from top. Then calculate the position for the current time, and adjust the constant of the constraint. I didn't need to use reloadData() or anything on the tableview, that might have made new cells appear "on top" of that view, covering it. But I actually never ran into such a problem. This way I didn't have to worry if the overlay should be visible or not, when user scrolled away from current time, then back, etc.

**Comment by zapjonny** [comment]
In viewDidload


```
self.tableviewTimetable.addSubview(self.viewGreenline) // Green line is the "now line", shown over current time in timetable.
```

Then I did this ONCE in viewDidLayoutSubviews

```
			if let parent = self.viewGreenline.superview, let green = self.viewGreenline {
				//print("Autolayout self.viewGreenline")
				green.translatesAutoresizingMaskIntoConstraints = false

				green.translatesAutoresizingMaskIntoConstraints = false

				let options: NSLayoutFormatOptions = []

				let horizontalconstraints = NSLayoutConstraint.constraints(withVisualFormat: "H:|[green]|",
				                                                           options: options,
				                                                           metrics: nil,
				                                                           views: [
																			"green": green,
																			])
				for cons in horizontalconstraints {
					cons.isActive = true
				}

				let topconstraint = green.topAnchor.constraint(equalTo: parent.topAnchor, constant: 111.0)
				topconstraint.isActive = true

				topconstraint.priority = UILayoutPriorityRequired
				let verticalconstraints = [topconstraint]
				self.constraintsGreenline = verticalconstraints
			}

```

Then I used a repeating timer (like every 5 seconds or so), updating the constant of `self.constraintsGreenline`... That's all.

**Comment by zapjonny** [comment]
I am thinking, what would be really handy, is if there was a designated "overlay" layer/view of UITableView/SpreadsheetView, to which I could safely add views and don't have to worry about the implementation changes someday which could break my overlay views.
So the overlay layer would allow adding stuff and positioning them over the cells using normal frames and/or autolayout.

**Comment by kishikawakatsumi** [comment]
I understand what you are saying and current spreadsheet view's behavior is unintentional. I thought the behavior is the same as `UITableView`'s, but isn't. The view added to spreadsheet view doesn't scroll together, it's like floating. It is due to the internal implementation. I try to fix it, but it is not a high priority for now. Thank you for pointing out that!

**Comment by zapjonny** [comment]
Yes, that's why I figure to achieve what I need to do, I have to add overlay views onto the internal tableView, but somehow it doesn't work. Maybe I made some mistake somewhere. Looking for the problem now.

**Comment by zapjonny** [comment]
I was able to add a view as an overlay if adding to the internal `columnHeaderView` which I made public. I had to make `ScrollView` public too.
In the app I needed to set `columnHeaderView.clipsToBounds = false`.
