### ISSUE TITLE
A view on a cell doesn't receive any touch events

### ISSUE THREAD

**Issue by kishikawakatsumi** [bannzai/SpreadsheetView#34]
Originally reported https://github.com/kishikawakatsumi/SpreadsheetView/issues/26

**Comment by zapjonny** [comment]
@kishikawakatsumi Sorry to bump again but I still cannot receive any touch to a `UIButton` within a cell. I also tried using a Tap Gesture Recognizer, but it also just does not work.

I am thinking I should try to reproduce the problem within the example project... If I can I will send you.

**Comment by zapjonny** [comment]
@kishikawakatsumi I added a `UIButton` to SlotCell. It does not receive any touches.
https://github.com/zapjonny/SpreadsheetView/tree/button_test_timetable

**Comment by kishikawakatsumi** [comment]
@zapjonny Figured out that the cell was added by Storyboard doesn't receive touch events. The workaround is to add a button programmatically for now 🙏

**Comment by zapjonny** [comment]
I also added a tap recognizer to the main view of the cell, that actually worked but I think the delegate `didSelectItemAt` was then not called.

Thanks, I will definitely try to add a button programmatically.

**Comment by zapjonny** [comment]
> The workaround is to add a button programmatically for now

This worked. Thanks! This is enough for me, for now!
