### ISSUE TITLE
Support Objective-C only project

### ISSUE THREAD

**Issue by ayoze** [bannzai/SpreadsheetView#43]
Hello,

first of all, many thanks for this awesome library.

I am trying to use is in my Objective C project, but it seems it is not posible at all for now... the protocols (data source and delegate) are not available from the -Swift.h file, so there is no chance to implement them. Are you planning to make them available soon?

Thanks!

**Comment by kishikawakatsumi** [comment]
@ayoze I'd like to support Objective-C. But the priority is low. Because we can use Objective-C and Swift mixed in the single project. So if we'd like to use this library with an Objective-C project, we can write ViewController in Swift. If there are many people who wish to use this project with pure Objective-C, I consider changing the priority.

**Comment by adamhongmy** [comment]
Where can I vote for objective c? I need it too.

**Comment by hcrgithub** [comment]
Can we please have Objective-C version of it?

**Comment by hemangshah** [comment]
With the great evaluation of Swift language over Objective-C, I believe it's been already a great time to start creating a new project in Swift and to keep helping the old project with bridging header without generating a necessity of the great code in Swift for Objective-C. I have started my career in Objective-C back in twenty twelve and never wanted to replace it with Swift or any other language but now this mind set is changed happily!

**Comment by TiagoMaiaL** [comment]
Same situation here. If you change your mind, I'd be willing to help with this feature. Meanwhile, I'm going to try writing the controller in swift and see what happens.

**Comment by harrypotter30022003** [comment]
+1 please

**Comment by kishikawakatsumi** [comment]
@hemangshah Contribution is always welcome.

**Comment by juliusbtesh** [comment]
I been looking for an Objective-C solution for something like this as well

**Comment by juliusbtesh** [comment]
I'm not even sure how to get this working as it is inside my objective-c project. I would really like to get this working asap.
Thanks

**Comment by karosLi** [comment]
+1

**Comment by karosLi** [comment]
I just change the source code to expose delegate func in Objective C.

This a not pull request, just for your reference.
https://github.com/karosLi/SpreadsheetViewObjectiveDemo

**Comment by keshiim** [comment]
Hello，guys. I convert this awesome framework into Objective C project. If one of you interesting about it, this link https://github.com/keshiim/ZMJGanttChart maybe you wanted. ^_^
