### ISSUE TITLE
ReloadData() doesn't refresh spreadsheetView

### ISSUE THREAD

**Issue by rogpfreck** [bannzai/SpreadsheetView#47]
Here's your GanttView, very slightly modified to demonstrate.

[GanttView.zip](https://github.com/kishikawakatsumi/SpreadsheetView/files/1014635/GanttView.zip)

If it isn't meant to work this way, is there a workaround?

Thanks

**Comment by kishikawakatsumi** [comment]
Duplicate of https://github.com/kishikawakatsumi/SpreadsheetView/issues/21, fixed by https://github.com/kishikawakatsumi/SpreadsheetView/pull/37.
Can you try the latest version?

**Comment by rogpfreck** [comment]
I’m using SpreadsheetView (0.6.2)

I see there’s a 0.6.3 ver. I’ll try that.

Thanks.

**Comment by rogpfreck** [comment]
Solved! It took a while.

I've been using cocoa pods, and using ver 0.6.2 of SpeadsheetView. When building my app with this configuration there's no effect using reloadData() one SpeadsheetView.

I had look at the Class demo from SpreadsheetView-master. ReloadData() worked. WTF! I decided to build the Class app as a separate app, using the 0.6.2 via pods. Compiled and worked well, but reloadData() didn't work! Getting closer to the solution.

So I built another Class app, but this time compiled the framework from your downloaded SpreadsheetView-master and embedded the framework into the new Class app. No pods this time. Everything worked including reloadData()!

I embedded the compiled SpreadsheetView framework into my own app, and bingo, reloadData() works well.

In case anyone's wondering. I tried the trick of taking 'pod SpreadsheetView' out of the podfile, running pod install, and then putting it back in and running pod install.  

I hope this helps anyone that's been struggling with the same problem.

Any thoughts, anyone?

**Comment by kishikawakatsumi** [comment]
@rogpfreck It is not unclear for me, probably you forgot to update CocoaPods master repo? CocoaPods doesn't update its spec repo automatically from 1.0, you need to execute `pod repo update` or `pod update` to update your local spec repo.

**Comment by rogpfreck** [comment]
I did that very recently. Looks like I'll have to do it again.

**Comment by rogpfreck** [comment]
Fixed. Thanks.
