### ISSUE TITLE
reloadData() doesn't refresh last 2/3 columns, row 1 of header

### ISSUE THREAD

**Issue by rogpfreck** [bannzai/SpreadsheetView#50]
This can be seen more easily by viewing one of the demo apps in landscape mode. Screenshots show GanttChart demo.

  func spreadsheetView(_ spreadsheetView: SpreadsheetView, didSelectItemAt indexPath: IndexPath) {
       
 print("Selected: (row: \(indexPath.row), column: \(indexPath.column))")

        spreadsheetView.reloadData()  // added 

    }

Add reloadData() to  _didSelectItemAt_ 

Scroll in landscape mode to the end of the display. Select a column to invoke didSelectItemAt. Some end columns are not refreshed. Bug applies to row 1 of header only.

![spreadsheeview reloaddata 1](https://cloud.githubusercontent.com/assets/13650919/26325569/50694fe0-3f2f-11e7-9440-995e7c82416a.png)
![spreadsheeview reloaddata 2](https://cloud.githubusercontent.com/assets/13650919/26325570/51ab2a68-3f2f-11e7-9766-9b7d22f8d96f.png)

**Comment by kishikawakatsumi** [comment]
@rogpfreck Thank you. This issue was fixed by https://github.com/kishikawakatsumi/SpreadsheetView/pull/54
