### ISSUE TITLE
Make it possible for SpreadsheetView to be subclassed

### ISSUE THREAD

**Issue by luksfarris** [bannzai/SpreadsheetView#52]
Hi @kishikawakatsumi , first of all, fantastic job on this, I specially loved how you did the tests.
Let me try to explain where I'm coming from:
> Say I want to have the same custom layout of SpreadsheetView across multiple View Controllers, it would be ideal to be able to subclass it, and have the custom behaviors on the init methods. 

That being said, your current implementation uses `public` for the class, which doesn't allow for it to be subclassed outside it's module.  I've create a pull request to change it to `open`.

Do you think this is a bad approach? Also, for some reason not all travis tests seem to be passing, but in my fork all your unit tests pass, and it compiles normally.

Thanks again, best regards

**Comment by kishikawakatsumi** [comment]
I will do it after releasing version 1.0.
