### ISSUE TITLE
`spreadsheetView:didDeselectItem` delegate not called when selecting a cell that should not be selected

### ISSUE THREAD

**Issue by luksfarris** [bannzai/SpreadsheetView#53]
Consider the following scenario:

Delegate `shouldSelectItemAt` is configured to select (0,0) but not (0,1).
1) When I select (0,0) it correctly selects it.
2) When I select (0,1) it correctly deselects (0,0) and does not select (0,1).

What I expected to happen: on action `2`, I expected `spreadsheetView:didDeselectItem` to be called, but it isn't. I will work on a pull request for this, but I'd like to hear your thoughts

**Comment by luksfarris** [comment]
I've just figured out `didUnhighlightItemAt` so I'm closing this issue.

Edit: It does not seem to work correctly :/ so I'm reopening

**Comment by kishikawakatsumi** [comment]
@luksfarris It's intended behavior. I made it match `UICollectionView`'s behavior. I also agree with you, the behavior that you said seems more intuitive and be preferable. However, I think that it is better that it matches collection view's behavior.

To be strict, the selection state is not changed at the action 2. The highlight state is unhighlighted, but keep selected. Scroll to bring the cell out of the screen, then scroll again to display the cell. You can see the cell is highlighted (=selected). So (it doesn't seem intuitive, but) `spreadsheetView:didDeselectItem` not being called is correct.

**Comment by luksfarris** [comment]
Hi, thanks for taking the time to answer it.
I understand your position, and will work around this. 
Feel free to close this issue 😉

**Comment by kishikawakatsumi** [comment]
@luksfarris Thanks!
