### ISSUE TITLE
Can't use pod to get SpreadsheetView

### ISSUE THREAD

**Issue by Smiacter** [bannzai/SpreadsheetView#58]
When I add pod 'SpreadsheetView' into my Podfile and run pod install, it show me "[!] Unable to find a specification for `SpreadsheetView`"
And I run pod search, it also couldn't find it.

Please check this, thx.

**Comment by kishikawakatsumi** [comment]
@Smiacter Can you please run `pod repo update`, then retry?

**Comment by Smiacter** [comment]
Ok, I'll try it, thx

**Comment by kishikawakatsumi** [comment]
Closing. Seems to be resolved.

**Comment by Smiacter** [comment]
OK, update pod fixed my problem. THX.

**Comment by nipun0505** [comment]
Hi, I am still having this issue. Tried, pod repo update but still getting this error[!] Unable to find a specification for `SpreadsheetView`

**Comment by kishikawakatsumi** [comment]
@nipun0505 There is a problem with your environment. Needs more info to investigate what is wrong.

**Comment by nipun0505** [comment]
Thanks for the quick reply. I am using cocoapods 0.39.0. Could that be an issue?
Here is the podfile:

```
source "https://github.com/CocoaPods/Old-Specs"
# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

def available_pods
	pod 'DZNEmptyDataSet', '~> 1.8.1'
	pod 'GoogleMaps', '~> 2.1.1'
	pod 'Fabric', '~> 1.6.11'
	pod 'Crashlytics', '~> 3.8.3'
	pod 'Buglife', '~> 1.3.3'
	pod 'TSMessages', '~> 0.9.12'
	pod 'MagicalRecord', '~> 2.3.2'
	pod 'AWSKinesis', '~> 2.4.12'
	pod 'AWSS3', '~> 2.4.12'
	pod 'AWSCognito', '~> 2.4.12'
    pod 'Flurry-iOS-SDK/FlurrySDK'
    pod 'Flurry-iOS-SDK/FlurryAds'
    pod 'MBCircularProgressBar'
    pod 'HMSegmentedControl'
    pod 'LMGaugeView'
    pod 'SDWebImage', '~>3.8'
    pod 'JVFloatLabeledTextField'
end

target 'MMMMM' do
	available_pods
end

target 'NNNNN' do
	available_pods
end

target 'VVVVV' do
	available_pods
end
```

**Comment by kishikawakatsumi** [comment]
0.39 is too old. Is there any reason not to update?

**Comment by kishikawakatsumi** [comment]
`source "https://github.com/CocoaPods/Old-Specs"` seems a cause of the issue.

**Comment by nipun0505** [comment]
Thanks, updating the pod version to 1.1.0 solved the issue. One query though, I am going to use it in an objective C project. Will I be able to adopt the protocols and do most of the stuff?? My requirement is to just display the data source which could be multiline. Since the data source methods ask for a width and height, I am assuming I can manipulate that.
