### ISSUE TITLE
Swift Package Manager?

### ISSUE THREAD

**Issue by patchthecode** [bannzai/SpreadsheetView#74]
1. Is it possible that you can restructure your project files so that is it compatible with `Swift Package Manager`?

2. Also, one question.
I maintain a [calendar project](https://github.com/patchthecode/JTAppleCalendar) and I was thinking of developing a `Calendar Schedule Week view`, but I stumbled across this excellent framework and was wondering if doing that library would be unnecessary.
Can someone create a Calendar WeekView using this framework?
Some thing like this?

Except with many functions etc that relates to dates/time rather than just working with a spreadsheet?

<img width="1071" alt="screen shot 2017-06-02 at 8 19 06 am" src="https://cloud.githubusercontent.com/assets/2439146/26732353/30bd4756-476c-11e7-9363-00b493fb8618.png">

If you do not have date/time related functions etc, then maybe I can use this framework as a dependency, and then wrap time/date functions around it.

**Comment by kishikawakatsumi** [comment]
@patchthecode 
> Note that at this time the Package Manager has no support for iOS, watchOS, or tvOS platforms.

https://github.com/apple/swift-package-manager/blob/f303078b2fd2f58e6ab9973442dbde79edfd3e58/Documentation/Usage.md#depending-on-apple-modules

**Comment by kishikawakatsumi** [comment]
I think the [Schedule](https://github.com/kishikawakatsumi/SpreadsheetView/tree/master/Examples/Schedule) example project is roughly close to the calendar week view.

I may add date/time related functions when supporting editing features in the future, but I have no plans at the moment.

Does it answer for you? @patchthecode

**Comment by patchthecode** [comment]
Yes it does. 
Thanks for the information.

**Comment by dinhletrieuduong** [comment]
I can't add SpreadsheetView to my project by SPM. It said /Package.swift has no Package.swift manifest. 
What should I do? Can anyone help me?
<img width="636" alt="Screen Shot 2022-11-21 at 14 08 00" src="https://user-images.githubusercontent.com/39703705/202986625-6f3b7234-14d8-4a1b-9ab8-d685003766dc.png">
