### ISSUE TITLE
Question: Cells appearing from bottom

### ISSUE THREAD

**Issue by zapjonny** [bannzai/SpreadsheetView#79]
Does this allow cells to appear from bottom and up?
Like, if you only have one cell, it would appear at bottom of the bounds of the SpreadsheetView. If you have two cells, the new cell (with row index 1) pushes the first cell 0 "up" one step.

```
+-----+
|     |
|     |
|     |
|row 0|
+-----+

+-----+
|     |
|     |
|row 0|
|row 1|
+-----+

+-----+
|     |
|row 0|
|row 1|
|row 2|
+-----+
```

I guess with a Spreadsheet view it might come down to implementation details, but I'm just checking if this is something that would be easily possible with the current SpreadsheetView framework.

**Comment by kishikawakatsumi** [comment]
@zapjonny It wasn't supported currently. I can probably add such feature as a configuration option. But it requires consideration, such as consistency with existing behavior.

**Comment by zapjonny** [comment]
Ok thanks I was able to create something similar to it yesterday. The problem is I likely need to use auto layout sized cells/rows, and I'm not sure I can pull that off any soon.

Maybe I can share my work so far later. The usual uitableview actually works mostly like this, the only difference is the direction cells align when the table view is not filling the outer frame height. Even with uicollectionview it seems to be hard.
