### ISSUE TITLE
ScrollToItem moves rows to the bottom

### ISSUE THREAD

**Issue by Romores** [bannzai/SpreadsheetView#81]
Hello, I seem to have an issue that I don't know how to solve.

I have a spreadsheet with a variable number of rows, and I noticed that if I use the ScrollToItem command when the height of all rows is lower than the SpreadsheetView's height, all the rows are moved to the bottom side of the view. This is not the kind of behaviour I'm looking for, as I want that the rows remain on the upper side exactly as they are created.

Is there a way to solve this, some kind of configuration I've missed, or is it a bug?

Thank you for helping me out.

**Comment by Romores** [comment]
Here's an animated gif that shows what happens.
I made so that by clicking on the first cell in the row, the spreadsheet scrolls to the start of the event relative to that particular row, but it also moves all the rows (including the frozen ones) to the bottom. I want the cells to remain on the upper side of the view.

![spreadsheet_glitch](https://user-images.githubusercontent.com/29062212/27259585-74af3c24-5416-11e7-9e34-b52885941854.gif)

**Comment by Romores** [comment]
I just noticed that the same happens on the right and left sides as well.

Basically, whenever there's space between the last row/column and the view, the table is moved to the opposite side.

**Comment by kishikawakatsumi** [comment]
@Romores Thanks for reporting. I will fix it soon.
