### ISSUE TITLE
How to draw Gantt Chart with percentage of work in iOS?

### ISSUE THREAD

**Issue by gauraveleven** [bannzai/SpreadsheetView#82]
Sir,
I am using "kishikawakatsumi/SpreadsheetView" library provide by you.I am facing issue to draw to chart basis on percentage of work day-wise and link the two progress of different task. So could you please tell me how to edit this existing library according to my task provide by you. Please  check attached screens.

I am trying from past 10 days but I am not able to get the solution. Please help me Sir.

Thank you so much in Advance.

![screen shot 2017-06-23 at 5 57 07 pm](https://user-images.githubusercontent.com/28773405/27482098-a50bbebc-583d-11e7-8943-beb7e12ad53d.png)

![screen shot 2017-06-23 at 5 57 18 pm](https://user-images.githubusercontent.com/28773405/27482110-adee678c-583d-11e7-9f8d-04c12ae0a0ae.png)

Regards
Gaurav Saini

**Comment by Romores** [comment]
For the first one, maybe you could try creating a nib containing a sort of progress bar to use as a reusable cell for the various tasks, and changing the value of the progress bar in the datasource method. I have never tried something like that, but I believe it could work.

Regarding the second request, I have no idea, sorry. It looks very specific and out of the scope of this library as it is. Maybe you could try something with Core Graphics or something like that, to draw the lines.
