### ISSUE TITLE
Crash when in a View Controller that is in a Navigation Controller

### ISSUE THREAD

**Issue by patsluth** [bannzai/SpreadsheetView#83]
`2017-06-23 12:56:36.195516-0600 GanttChart[76766:20191693] -[SpreadsheetView.SpreadsheetView refreshControl]: unrecognized selector sent to instance 0x7fc0fdc08570
2017-06-23 12:56:36.200924-0600 GanttChart[76766:20191693] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SpreadsheetView.SpreadsheetView refreshControl]: unrecognized selector sent to instance 0x7fc0fdc08570'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000108b72f6b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001052fb121 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000108bfd494 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKit                               0x00000001061f8c55 -[UIResponder doesNotRecognizeSelector:] + 295
	4   CoreFoundation                      0x0000000108af6858 ___forwarding___ + 1432
	5   CoreFoundation                      0x0000000108af6238 _CF_forwarding_prep_0 + 120
	6   UIKit                               0x0000000106626fca +[_UINavigationControllerRefreshControlHost canHostRefreshControlOwnedByScrollView:inNavigationController:] + 233
	7   UIKit                               0x00000001061bf9c6 -[UINavigationController _updateNavigationBarHostedRefreshControlToHostRefreshControlForScrollView:] + 180
	8   UIKit                               0x00000001061bfd65 -[UINavigationController _layoutViewController:] + 149
	9   UIKit                               0x00000001061c0633 -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 463
	10  UIKit                               0x00000001061c07e4 -[UINavigationController _startTransition:fromViewController:toViewController:] + 153
	11  UIKit                               0x00000001061c1904 -[UINavigationController _startDeferredTransitionIfNeeded:] + 857
	12  UIKit                               0x00000001061c2bd2 -[UINavigationController __viewWillLayoutSubviews] + 140
	13  UIKit                               0x00000001063ff955 -[UILayoutContainerView layoutSubviews] + 231
	14  UIKit                               0x00000001060b38d8 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1281
	15  QuartzCore                          0x00000001090cd729 -[CALayer layoutSublayers] + 146
	16  QuartzCore                          0x00000001090c090a _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 370
	17  QuartzCore                          0x00000001090c0784 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	18  QuartzCore                          0x000000010904f2f0 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 326
	19  QuartzCore                          0x000000010907b79c _ZN2CA11Transaction6commitEv + 480
	20  UIKit                               0x0000000106004190 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 141
	21  CoreFoundation                      0x0000000108b1695c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	22  CoreFoundation                      0x0000000108afafeb __CFRunLoopDoBlocks + 203
	23  CoreFoundation                      0x0000000108afa7e4 __CFRunLoopRun + 1060
	24  CoreFoundation                      0x0000000108afa149 CFRunLoopRunSpecific + 409
	25  GraphicsServices                    0x000000010c2e99d7 GSEventRunModal + 62
	26  UIKit                               0x0000000105fe891d UIApplicationMain + 159
	27  GanttChart                          0x00000001048c97a7 main + 55
	28  libdyld.dylib                       0x000000010a68cb65 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

Reproduce by using any of the example projects. Go to main.storyboard and add a navigation controller. Set the example view controller as the root view controller of the navigation controller.

**Comment by kishikawakatsumi** [comment]
@patsluth Can you please share/send me the reproducible project?

**Comment by patsluth** [comment]
The only change I made was to the GanttChart example project Main.storyboard file. Thanks for looking into this.

[SpreadsheetView-master 2.zip](https://github.com/kishikawakatsumi/SpreadsheetView/files/1102227/SpreadsheetView-master.2.zip)

**Comment by kishikawakatsumi** [comment]
@patsluth I cannot reproduce the crash yet. I've built & run the app using Xcode 8.3.2 with iPhone 7 and 7 Plus simulator, and drag around randomly and things seemed fairly smooth. What steps specifically need to be followed in order to trigger the crash?

**Comment by patsluth** [comment]
My apologies, this is for the Xcode 9 beta. Simply adding a SpreadsheetView in any UIViewController with a UINavigationView would cause a crash. (Either in IB or in code)

**Comment by kishikawakatsumi** [comment]
@patsluth Thanks. It is probably the side-effect of changing the behavior of "automatically adjust scroll view insets" on iOS 11. I'll fix it.

**Comment by orazz** [comment]
Did u solve this problem? Can i get this update?
