### ISSUE TITLE
Enabling paging

### ISSUE THREAD

**Issue by lukejones1** [bannzai/SpreadsheetView#86]
Can't seem to enable paging at all. Crashes with reason `[SpreadsheetView.SpreadsheetView _adjustedVerticalOffsetPinnedToScrollableBounds:]: unrecognized selector sent to instance 0x7f9a34f20d20`

**Comment by kishikawakatsumi** [comment]
What's version of iOS?

**Comment by lukejones1** [comment]
iOS 10.2

**Comment by kishikawakatsumi** [comment]
@lukejones1 Could you provide reproducible sample code? I cannot reproducible the crash.

**Comment by lukejones1** [comment]
Not doing anything new as such.  I've just added the minimum requirements to get started.


    class ViewController: UIViewController {
    
    lazy var spreadsheetView : SpreadsheetView = {
        let view = SpreadsheetView()
        view.delegate = self
        view.dataSource = self
        view.showsHorizontalScrollIndicator = false
        view.intercellSpacing = CGSize(width: 0, height: 0)
        view.isPagingEnabled = true
        return view
    }()
    

    override func viewDidLoad() {
        super.viewDidLoad()
        setupViews()
    }
 
    func setupViews() {
        view.addSubview(spreadsheetView)  
        spreadsheetView.fillSuperview()
    }
    }


    extension ViewController: SpreadsheetViewDataSource, SpreadsheetViewDelegate {
    
    func numberOfColumns(in spreadsheetView: SpreadsheetView) -> Int {
        return 4
    }
    
    func numberOfRows(in spreadsheetView: SpreadsheetView) -> Int {
        return 24
    }
    
    func spreadsheetView(_ spreadsheetView: SpreadsheetView, widthForColumn column: Int) -> CGFloat {
        if column == 0 {
            return 40
        } else {
            return view.frame.width - 40
        }
    }
    
    func spreadsheetView(_ spreadsheetView: SpreadsheetView, heightForRow row: Int) -> CGFloat {
        return 60
    }
    
    func frozenColumns(in spreadsheetView: SpreadsheetView) -> Int {
        return 1
    }
    }

The crash occurs when I scroll horizontally to the last column

**Comment by kishikawakatsumi** [comment]
Thanks. I'll look into it tonight.

**Comment by Romores** [comment]
I tried this too, and the error is pretty much the same.
