### ISSUE TITLE
Change frozen rows/columns on runtime

### ISSUE THREAD

**Issue by Noitidart** [bannzai/SpreadsheetView#94]
Hi there,

I need to change the number of columns that are frozen. I tried to set `spreadsheetView.frozenColumns` but this is get-only. Is this possible?

**Comment by kishikawakatsumi** [comment]
@Noitidart You can use dataSource method instead. `spreadsheetView.frozenColumns` is a convenience API to retrieve current setting. SpreadsheetView is almost same usage for UITableView and UICollectionView.

**Comment by kishikawakatsumi** [comment]
If you have further questions, please feel free to reopen this issue.

**Comment by Noitidart** [comment]
Thank you very much @kishikawakatsumi I'm actually not a Swift guy, do you mean I can do this:

```
spreadsheetView.dataSource.setFrozenColumns(2)
```

**Comment by kishikawakatsumi** [comment]
@Noitidart No, `SpreadsheetViewDataSource` doesn't have such property/setter. You need to implement data source method first,

```
func frozenRows(in spreadsheetView: SpreadsheetView) -> Int {
    return frozonRowCount
}
```

Then change `frozonRowCount`, call `spreadsheetView.reloadData()` to reflect current state. Probably you should learn basic iOS programming first.

**Comment by Noitidart** [comment]
Thank you sir for those details. I will try it out. Thanks also for pointing out this is the basics, I was constrained by time so needed a working solution, but I will try to learn the basics relevant to this, if you have any related articles or messages I would really appreciate it.
