### ISSUE TITLE
crash on iOS 11

### ISSUE THREAD

**Issue by orazz** [bannzai/SpreadsheetView#95]
Did you solve this bug on iOS 11?

**Comment by kishikawakatsumi** [comment]
@orazz Could you please provide more details? Can you provide a reproducible sample code?

**Comment by kishikawakatsumi** [comment]
Closing, lack of information and no response. Feel free to reopen if you can provide more details.

**Comment by orazz** [comment]
Tested in XCode 9, iOS 11. bug fixed thanks.
